version: '3.9'
services:
  code-challenge:
    container_name: code-challenge
    image: code-challenge
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
      - rabbitmq
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/challenge
        - SPRING_RABBITMQ_HOST=rabbitmq
  postgresql:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=challenge
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq-challenge'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres-data:
    external: true